export const LOCALE_STORAGE_KEY = "app_locale";

export function resolveLocale() {
  try {
    const qsLang = new URLSearchParams(window.location.search).get("lang");
    const normalizedQs = String(qsLang || "").toLowerCase();
    if (normalizedQs === "ru" || normalizedQs === "en") {
      localStorage.setItem(LOCALE_STORAGE_KEY, normalizedQs);
      return normalizedQs;
    }
    const saved = String(localStorage.getItem(LOCALE_STORAGE_KEY) || "").toLowerCase();
    if (saved === "ru" || saved === "en") return saved;
    const browser = String(navigator.language || "").toLowerCase();
    return browser.startsWith("ru") ? "ru" : "en";
  } catch {
    return "en";
  }
}

export const AI_MODEL_FORM_COPY = {
  en: {
    modeFromScratch: "From Scratch",
    modeFromPhotos: "From Photos",
    modelLooksTitle: "Model Looks * (every category required)",
    modelLooksProgress: "{done}/{total} selected",
    modelLooksMissingHint: "Still need: {missing}",
    customChip: "Custom",
    typeCustomPlaceholder: "Type custom…",
    ageLabel: "Age *",
    agePlaceholder: "e.g. 25",
    referencePromptLabel: "Reference Prompt",
    optional: "(Optional)",
    referencePromptHint: "Must be non-explicit (for reference image)",
    referencePromptPlaceholder: "e.g. freckles, dimples, long wavy hair",
    pricingTitle: "Pricing",
    pricingStep1: "Step 1: Face Reference",
    pricingStep2: "Step 2: Full Model (poses)",
    pricingTotal: "Total (paid upfront)",
    back: "Back",
    getCredits: "Get Credits",
    generating: "Generating...",
    generateReference: "Generate Reference",
    fromPhotosBlurb:
      "Upload reference photos and write prompts for each shot. Set age and gender (or use Auto-detect looks). The generator uses these to keep the 3 outputs consistent. Cost:",
    ageGenderCaption: "Age & gender (used for all 3 photos)",
    genderLabel: "Gender",
    autoDetectLooks: "Auto-detect looks",
    photoSelfieLabel: "Selfie (1:1)",
    photoPortraitLabel: "Portrait (3:4)",
    photoFullBodyLabel: "Full Body (9:16)",
    copyToAll: "Copy to all",
    photoSingular: "photo",
    photoPlural: "photos",
    photoCount: "{count} photo(s)",
    toastUploadRefFirst: "Upload a reference photo first",
    toastPromptFromPhoto: "Prompt filled from photo",
    toastAnalyzeFail: "Failed to analyze photo",
    toastMaxPhotos: "Maximum 5 reference photos per section",
    toastUploadOk: "Uploaded {count} photo(s)",
    toastUploadFailed: "Upload failed",
    uploading: "Uploading...",
    addRefPhotos: "Add reference photos (1-5)",
    addMorePhotos: "Add more ({n}/5)",
    photoPromptPh0:
      "Describe the selfie... e.g. 'smiling, natural lighting, casual look'",
    photoPromptPh1:
      "Describe the portrait... e.g. 'soft lighting, elegant, slight smile'",
    photoPromptPh2:
      "Describe the full body shot... e.g. 'standing pose, beach, summer outfit'",
    analyzing: "Analyzing...",
    autoFill: "Auto-fill",
    refAlt: "Ref",
    generateFromPhotos: "Generate",
    toastSelectGender: "Please select a gender",
    toastPleaseGender: "Please select a gender",
    toastSelectAllChips: "Please select every appearance category — still missing: {missing}",
    toastEnterAge: "Please enter age (1-90)",
    overlayTitleRef: "Generating Reference Image",
    overlayTitlePhotos: "Generating Model Photos",
    overlaySubRef: "Creating your AI model reference...",
    overlaySubPhotos: "This may take 1-2 minutes",
    overlayFooterRef: "Generating reference portrait from your parameters...",
    overlayFooterStep: "Step {step}/3: {label}",
    overlayStepProcessing: "Processing",
    poseStep1: "Close-up Selfie",
    poseStep2: "Portrait",
    poseStep3: "Full Body Shot",
    toastCopiedAll: "Copied to all photos",
    toastUploadSelfieFirst: "Upload at least one reference photo in Selfie, then try Auto-detect looks.",
    toastLooksDetected: "Looks detected. Adjust age/gender or chips if needed.",
    toastDetectFail: "Could not detect looks. Set age and gender manually.",
    toastDetectError: "Auto-detect failed. Set age and gender manually.",
    toastEachPhoto: "Each photo needs at least one reference image",
    toastEachPrompt: "Each photo needs a prompt",
    toastAgeRange: "Age must be between 1 and 120",
    toastModelCreated: 'AI Model "{name}" created successfully!',
    toastGenFailed: "Model generation failed — please try again.",
    toastStillGen: "Model is still generating — check your Models page in a few minutes.",
    toastNoRef: "No reference image available",
    previewTitle: "Reference Image",
    previewSubtitle: "This is your AI model's base appearance",
    refAltLarge: "Reference",
    regenerateFace: "Regenerate Face",
    customizePoses: "Customize Model Poses",
    finishCardTitle: "Finish Your AI Model",
    finishCardBadge: "Included",
    finishCardBody:
      "Creates 3 poses: Close-up, Portrait & Full Body (already paid in step 1)",
    edit: "Edit",
    generateModel: "Generate Model",
    progressGenRef: "Generating reference image...",
    progressRegenRef: "Regenerating reference image...",
    progressCloseSelfie: "Generating close-up selfie...",
    progressHoldTight: "Generating your AI model… hold tight",
    progressPhoto1: "Generating photo 1… ({t})",
    progressPhoto23: "Photo 1 done — generating photos 2 & 3… ({t})",
    progressAlmost: "Almost done — finishing last photo… ({t})",
    progressFinal: "Finalizing… ({t})",
    progressPoll0: "Generating close-up selfie… ({t})",
    progressPoll1: "Selfie done — generating portrait & full body… ({t})",
    progressPoll2: "Almost done — finishing last photo… ({t})",
    toastRefOk: "Reference image generated!",
    toastRefFail: "Failed to generate reference image",
    toastRefRegenOk: "New reference image generated!",
    toastRefRegenFail: "Failed to regenerate reference image",
    toastModelOk: 'AI Model "{name}" created successfully!',
    toastPosesFail: "Failed to generate model poses",
    failedGen: "Failed to generate model",
    failedGenModel: "Failed to generate model",
  },
  ru: {
    modeFromScratch: "С нуля",
    modeFromPhotos: "По фото",
    modelLooksTitle: "Внешность модели * (нужны все категории)",
    modelLooksProgress: "выбрано {done}/{total}",
    modelLooksMissingHint: "Осталось выбрать: {missing}",
    customChip: "Свой",
    typeCustomPlaceholder: "Введите свой вариант…",
    ageLabel: "Возраст *",
    agePlaceholder: "напр. 25",
    referencePromptLabel: "Промпт к референсу",
    optional: "(необязательно)",
    referencePromptHint: "Без откровенного контента (для референсного изображения)",
    referencePromptPlaceholder: "напр. веснушки, ямочки, длинные волнистые волосы",
    pricingTitle: "Стоимость",
    pricingStep1: "Шаг 1: референс лица",
    pricingStep2: "Шаг 2: полная модель (позы)",
    pricingTotal: "Итого (всё сразу)",
    back: "Назад",
    getCredits: "Получить кредиты",
    generating: "Генерация...",
    generateReference: "Создать референс",
    fromPhotosBlurb:
      "Загрузите референсные фото и напишите промпт для каждого кадра. Укажите возраст и пол (или используйте автоопределение внешности). Генератор сохранит единообразие всех 3 результатов. Стоимость:",
    ageGenderCaption: "Возраст и пол (для всех 3 фото)",
    genderLabel: "Пол",
    autoDetectLooks: "Авто определить внешность",
    photoSelfieLabel: "Селфи (1:1)",
    photoPortraitLabel: "Портрет (3:4)",
    photoFullBodyLabel: "В полный рост (9:16)",
    copyToAll: "Копировать во все",
    photoSingular: "фото",
    photoPlural: "фото",
    photoCount: "{count} фото",
    toastUploadRefFirst: "Сначала загрузите референсное фото",
    toastPromptFromPhoto: "Промпт заполнен по фото",
    toastAnalyzeFail: "Не удалось проанализировать фото",
    toastMaxPhotos: "Не больше 5 референсных фото на секцию",
    toastUploadOk: "Загружено фото: {count}",
    toastUploadFailed: "Ошибка загрузки",
    uploading: "Загрузка...",
    addRefPhotos: "Добавить референсы (1–5)",
    addMorePhotos: "Ещё ({n}/5)",
    photoPromptPh0:
      "Опишите селфи… напр. «улыбка, естественный свет, casual»",
    photoPromptPh1:
      "Опишите портрет… напр. «мягкий свет, элегантность, лёгкая улыбка»",
    photoPromptPh2:
      "Опишите кадр в полный рост… напр. «стоит, пляж, летний образ»",
    analyzing: "Анализ...",
    autoFill: "Авто",
    refAlt: "Реф",
    generateFromPhotos: "Создать",
    toastSelectGender: "Выберите пол",
    toastPleaseGender: "Выберите пол",
    toastSelectAllChips: "Выберите все категории внешности — не хватает: {missing}",
    toastEnterAge: "Укажите возраст (1–90)",
    overlayTitleRef: "Создаём референсное изображение",
    overlayTitlePhotos: "Создаём фото модели",
    overlaySubRef: "Создаём референсный портрет по вашим параметрам...",
    overlaySubPhotos: "Это может занять 1–2 минуты",
    overlayFooterRef: "Генерация референсного портрета по параметрам...",
    overlayFooterStep: "Шаг {step}/3: {label}",
    overlayStepProcessing: "Обработка",
    poseStep1: "Крупное селфи",
    poseStep2: "Портрет",
    poseStep3: "В полный рост",
    toastCopiedAll: "Скопировано во все фото",
    toastUploadSelfieFirst: "Сначала загрузите референс в блоке «Селфи», затем попробуйте автоопределение.",
    toastLooksDetected: "Внешность определена. При необходимости подправьте возраст, пол или чипы.",
    toastDetectFail: "Не удалось определить внешность. Укажите возраст и пол вручную.",
    toastDetectError: "Ошибка автоопределения. Укажите возраст и пол вручную.",
    toastEachPhoto: "Для каждого фото нужен хотя бы один референс",
    toastEachPrompt: "Для каждого фото нужен промпт",
    toastAgeRange: "Возраст должен быть от 1 до 120",
    toastModelCreated: 'ИИ-модель «{name}» создана!',
    toastGenFailed: "Не удалось сгенерировать модель — попробуйте снова.",
    toastStillGen: "Модель всё ещё генерируется — проверьте страницу «Модели» через несколько минут.",
    toastNoRef: "Нет референсного изображения",
    previewTitle: "Референсное изображение",
    previewSubtitle: "Базовая внешность вашей ИИ-модели",
    refAltLarge: "Референс",
    regenerateFace: "Пересоздать лицо",
    customizePoses: "Настроить позы модели",
    finishCardTitle: "Завершить ИИ-модель",
    finishCardBadge: "Включено",
    finishCardBody:
      "Создаёт 3 позы: крупный план, портрет и в полный рост (уже оплачено на шаге 1)",
    edit: "Изменить",
    generateModel: "Создать модель",
    progressGenRef: "Создаём референсное изображение...",
    progressRegenRef: "Пересоздаём референсное изображение...",
    progressCloseSelfie: "Создаём крупное селфи...",
    progressHoldTight: "Создаём вашу ИИ-модель… подождите",
    progressPhoto1: "Фото 1… ({t})",
    progressPhoto23: "Фото 1 готово — создаём 2 и 3… ({t})",
    progressAlmost: "Почти готово — финальное фото… ({t})",
    progressFinal: "Завершение… ({t})",
    progressPoll0: "Крупное селфи… ({t})",
    progressPoll1: "Селфи готово — портрет и полный рост… ({t})",
    progressPoll2: "Почти готово — последнее фото… ({t})",
    toastRefOk: "Референсное изображение создано!",
    toastRefFail: "Не удалось создать референс",
    toastRefRegenOk: "Новый референс создан!",
    toastRefRegenFail: "Не удалось пересоздать референс",
    toastModelOk: 'ИИ-модель «{name}» создана!',
    toastPosesFail: "Не удалось сгенерировать позы модели",
    failedGen: "Не удалось создать модель",
    failedGenModel: "Не удалось создать модель",
  },
};

export function formatCopy(template, vars) {
  if (!template) return "";
  return template.replace(/\{(\w+)\}/g, (_, k) =>
    vars && vars[k] != null ? String(vars[k]) : ""
  );
}
